# Generated by Django 3.1.3 on 2020-11-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=3, unique=True)),
                ('num_code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('unit', models.IntegerField(default=1)),
                ('currency_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='1970-01-01')),
                ('rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('curr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter_frontend.currencies')),
            ],
        ),
    ]
