# Generated by Django 3.1.3 on 2020-12-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='unit',
        ),
        migrations.AddField(
            model_name='rates',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
