name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python website/manage.py test

  deploy:
    - name: Deploy Django via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.WEB_HOST }}
        username: ${{ secrets.PROJECT_USER }}
        port: ${{ secrets.WEB_HOST_PORT }}
        key: ${{ secrets.PROJECT_USER_KEY }}
        source: "website/*"
        target: "website"
        strip_components: 1

    - name: Collect static assets
      run: |
        ssh ${{ secrets.PROJECT_USER }}@${{ secrets.WEB_HOST }} -p ${{ secrets.WEB_HOST_PORT }} -C "python website/manage.py collectstatic"
    - name: Restart application server
      run: |
        ssh ${{ secrets.PROJECT_USER }}@${{ secrets.WEB_HOST }} -p ${{ secrets.WEB_HOST_PORT }} -C "sudo /usr/bin/systemctl restart uwsgi-app@gb.service"